name = "foam"
defaultTargets = ["Core", "Foam", "Toy", "Counter"]

[[lean_lib]]
name = "Core"
srcDir = "grown"

[[lean_lib]]
name = "Foam"
srcDir = "grown"

[[lean_lib]]
name = "Toy"
srcDir = "grown"

[[lean_lib]]
name = "Counter"
srcDir = "grown"
