name = "foam"
defaultTargets = ["Room", "Face", "Witness", "Toy", "Counter", "Seek", "Eih"]

[[lean_lib]]
name = "Room"
srcDir = "grown"

[[lean_lib]]
name = "Face"
srcDir = "grown"

[[lean_lib]]
name = "Toy"
srcDir = "grown"

[[lean_lib]]
name = "Counter"
srcDir = "grown"

[[lean_lib]]
name = "Pieces"
srcDir = "bin"

[[lean_lib]]
name = "Seek"
srcDir = "grown"

[[lean_lib]]
name = "Eih"
srcDir = "grown"

[[lean_lib]]
name = "Witness"
srcDir = "grown"
