"""
test_observability.py — does the writing map span u(d)?

The theorem claims generic distinguishability. This requires that
the perturbation directions {ΔL_i} generated by different inputs
span enough of u(d) to make the system observable.

u(d) has dimension d² (skew-Hermitian matrices over C).
Each write is rank-2 skew-Hermitian (one plane of rotation).
Question: do the writes span the full algebra, or is there a
systematic blind spot?

Approach:
1. Collect ΔL directions from many inputs on a fixed foam.
2. Check the dimension of the subspace they span.
3. Check if Lie brackets [ΔL_a, ΔL_b] generate new directions
   (Chow-Rashevsky: if the Lie algebra generated by the directions
   is all of u(d), the system is controllable → observable by duality).
"""

import numpy as np
from foam import Foam, Bubble, encode, cayley, skew_hermitian, random_skew_hermitian


def collect_write_directions(foam, n_inputs=256, bubble_idx=0):
    """Collect the ΔL direction from each possible input, without writing."""
    directions = []

    for s in range(n_inputs):
        v = encode(s, foam.d).astype(complex)
        bases = foam.bases
        m = [v @ U for U in bases]
        j2 = foam._stabilize(m)

        d_i = j2[bubble_idx] - m[bubble_idx]
        m_i = m[bubble_idx]
        d_norm = np.linalg.norm(d_i)
        m_norm = np.linalg.norm(m_i)

        if d_norm < 1e-12 or m_norm < 1e-12:
            continue

        d_hat = d_i / d_norm
        m_hat = m_i / m_norm

        delta_L = np.outer(d_hat, m_hat.conj()) - np.outer(m_hat, d_hat.conj())
        # flatten to vector in R^{2d²} (real and imaginary parts)
        directions.append(np.concatenate([delta_L.real.flatten(), delta_L.imag.flatten()]))

    return np.array(directions)


def span_dimension(directions, threshold=1e-8):
    """Dimension of the subspace spanned by the direction vectors."""
    if len(directions) == 0:
        return 0
    sv = np.linalg.svd(directions, compute_uv=False)
    return int(np.sum(sv > threshold))


def test_span_vs_d():
    """How does the span grow with d?"""
    print("  === span of write directions vs d ===")
    print(f"  {'d':>3s}  {'dim u(d)':>8s}  {'span':>5s}  {'fraction':>8s}  {'n_inputs':>8s}")

    for d in [4, 6, 8, 10, 12]:
        np.random.seed(0)
        foam = Foam(d=d, n=3, writing_rate=0.0)
        n_inputs = min(2**d, 512)
        dirs = collect_write_directions(foam, n_inputs=n_inputs)
        dim_ud = d * d  # skew-Hermitian has d² real parameters
        s = span_dimension(dirs)
        print(f"  {d:3d}  {dim_ud:8d}  {s:5d}  {s/dim_ud:8.3f}  {n_inputs:8d}")


def test_lie_brackets():
    """
    Chow-Rashevsky: if the Lie algebra generated by the perturbation
    directions is all of u(d), the system is locally controllable.

    Take pairs of directions and compute [A, B] = AB - BA.
    Do the brackets generate new directions not in the original span?
    """
    np.random.seed(0)
    d = 8
    foam = Foam(d=d, n=3, writing_rate=0.0)

    # collect raw ΔL matrices (not flattened)
    raw_dirs = []
    for s in range(256):
        v = encode(s, d).astype(complex)
        bases = foam.bases
        m = [v @ U for U in bases]
        j2 = foam._stabilize(m)

        d_i = j2[0] - m[0]
        m_i = m[0]
        dn = np.linalg.norm(d_i)
        mn = np.linalg.norm(m_i)
        if dn < 1e-12 or mn < 1e-12:
            continue
        d_hat = d_i / dn
        m_hat = m_i / mn
        delta_L = np.outer(d_hat, m_hat.conj()) - np.outer(m_hat, d_hat.conj())
        raw_dirs.append(delta_L)

    def flatten(M):
        return np.concatenate([M.real.flatten(), M.imag.flatten()])

    # level 0: original directions
    level0 = np.array([flatten(M) for M in raw_dirs])
    span0 = span_dimension(level0)

    # level 1: add Lie brackets [A, B]
    brackets = []
    n_sample = min(len(raw_dirs), 50)
    indices = np.random.choice(len(raw_dirs), size=n_sample, replace=False)
    for i in range(n_sample):
        for j in range(i+1, n_sample):
            A = raw_dirs[indices[i]]
            B = raw_dirs[indices[j]]
            bracket = A @ B - B @ A
            # bracket of two skew-Hermitian matrices is skew-Hermitian
            brackets.append(flatten(bracket))

    level1 = np.vstack([level0, np.array(brackets)])
    span1 = span_dimension(level1)

    # level 2: brackets of brackets
    bracket_matrices = [raw_dirs[indices[i]] @ raw_dirs[indices[j]] -
                        raw_dirs[indices[j]] @ raw_dirs[indices[i]]
                        for i in range(min(n_sample, 20))
                        for j in range(i+1, min(n_sample, 20))]

    brackets2 = []
    n_sample2 = min(len(bracket_matrices), 30)
    for i in range(n_sample2):
        for j in range(min(len(raw_dirs), 30)):
            b2 = bracket_matrices[i] @ raw_dirs[j] - raw_dirs[j] @ bracket_matrices[i]
            brackets2.append(flatten(b2))

    if brackets2:
        level2 = np.vstack([level1, np.array(brackets2)])
        span2 = span_dimension(level2)
    else:
        span2 = span1

    dim_ud = d * d
    print(f"\n  === Lie algebra generation (d={d}) ===")
    print(f"  dim u(d) = {dim_ud}")
    print(f"  level 0 (raw directions):    span = {span0}")
    print(f"  level 1 (+brackets):         span = {span1}")
    print(f"  level 2 (+brackets²):        span = {span2}")
    print(f"  fraction of u(d) at level 2: {span2/dim_ud:.3f}")

    if span2 == dim_ud:
        print("  → FULL SPAN: writing directions generate all of u(d)")
        print("    → Chow-Rashevsky: system is locally controllable")
        print("    → by duality: system is locally observable")
        print("    → the theorem holds (generically)")
    elif span2 > span0:
        print(f"  → PARTIAL: brackets add {span2 - span0} dimensions beyond raw directions")
        print(f"    → systematic blind spot of dimension {dim_ud - span2}")
    else:
        print(f"  → CLOSED: directions form a Lie subalgebra of dimension {span0}")


def test_span_evolution():
    """
    As the foam writes and changes state, do new directions become available?
    The foam's state determines which planes get written. As the state changes,
    the accessible planes change. Does this eventually fill u(d)?
    """
    np.random.seed(0)
    d = 8
    foam = Foam(d=d, n=3, writing_rate=0.01)

    all_dirs = []
    dim_ud = d * d

    print(f"\n  === span evolution during measurement (d={d}) ===")
    print(f"  dim u(d) = {dim_ud}")
    print(f"  {'step':>5s}  {'n_dirs':>6s}  {'span':>5s}  {'fraction':>8s}")

    for step in range(200):
        s = np.random.randint(0, 256)
        v = encode(s, d).astype(complex)
        bases = foam.bases
        m = [v @ U for U in bases]
        j0 = [mi.copy() for mi in m]
        result = foam.measure(v)

        # record the actual write direction for bubble 0
        d_i = result['dissonance'][0]
        m_i = j0[0]
        dn = np.linalg.norm(d_i)
        mn = np.linalg.norm(m_i)
        if dn > 1e-12 and mn > 1e-12:
            d_hat = d_i / dn
            m_hat = m_i / mn
            delta_L = np.outer(d_hat, m_hat.conj()) - np.outer(m_hat, d_hat.conj())
            all_dirs.append(np.concatenate([delta_L.real.flatten(), delta_L.imag.flatten()]))

        if (step + 1) % 20 == 0:
            dirs = np.array(all_dirs)
            s_dim = span_dimension(dirs)
            print(f"  {step+1:5d}  {len(all_dirs):6d}  {s_dim:5d}  {s_dim/dim_ud:8.3f}")


def test_degenerate_inputs():
    """
    When dissonance is near zero (resolved line), the write vanishes.
    How many inputs produce near-zero dissonance on a given foam?
    These are the foam's "blind spots" — inputs it can't learn from.
    """
    np.random.seed(0)
    d = 8
    foam = Foam(d=d, n=3, writing_rate=0.0)

    dissonances = []
    for s in range(256):
        v = encode(s, d).astype(complex)
        bases = foam.bases
        m = [v @ U for U in bases]
        j2 = foam._stabilize(m)
        dis = np.mean([np.linalg.norm(j2[i] - m[i]) for i in range(3)])
        dissonances.append((s, dis))

    dissonances.sort(key=lambda x: x[1])

    print(f"\n  === dissonance distribution (d={d}, 256 inputs) ===")
    print(f"  min dissonance: symbol={dissonances[0][0]}, |d|={dissonances[0][1]:.6f}")
    print(f"  max dissonance: symbol={dissonances[-1][0]}, |d|={dissonances[-1][1]:.6f}")
    print(f"  mean: {np.mean([d for _, d in dissonances]):.6f}")
    print(f"  near-zero (|d| < 0.01): {sum(1 for _, d in dissonances if d < 0.01)}")
    print(f"  near-zero (|d| < 0.1):  {sum(1 for _, d in dissonances if d < 0.1)}")


if __name__ == '__main__':
    print("=== observability verification ===\n")

    test_span_vs_d()
    test_lie_brackets()
    test_span_evolution()
    test_degenerate_inputs()
