"""
Test: do two stacked R³ slices (re + im = C³) generate su(d)?

Setup: Observer has two R³ slices P_re and P_im.
- P_re reads Re(P @ m_i) — real part of complex measurement
- P_im reads Im(P @ m_i) — imaginary part
- Combined: complex vectors d = d_re + i*d_im, m = m_re + i*m_im
- Complex write: d⊗m† − m⊗d† (skew-Hermitian)

Question: does the Lie algebra generated by these complex writes
span su(d)? (Not just so(d).)

If yes: stacking two Taylor-valid R³ slices recovers su(d),
and π₁(SU(d)) = 0... wait, that's trivially connected.

Hmm. Let's check what we actually get.
"""

import numpy as np


def make_slice(d, rng):
    Q = np.linalg.qr(rng.standard_normal((d, 3)))[0]
    return Q[:, :3].T  # (3, d) real


def complex_write(d_re, d_im, m_re, m_im):
    """Skew-Hermitian write from complex vectors d = d_re + i*d_im, m = m_re + i*m_im.
    W = d ⊗ m† − m ⊗ d†
    """
    d_c = d_re + 1j * d_im
    m_c = m_re + 1j * m_im
    W = np.outer(d_c, m_c.conj()) - np.outer(m_c, d_c.conj())
    return W


def real_write(d_vec, m_vec):
    """Real skew-symmetric write."""
    return np.outer(d_vec, m_vec) - np.outer(m_vec, d_vec)


def commutator(A, B):
    return A @ B - B @ A


def lie_dim(generators, d):
    """Dimension of generated Lie algebra."""
    current = list(generators)
    M = np.array([g.flatten() for g in current])
    current_rank = np.linalg.matrix_rank(M, tol=1e-8)

    for _ in range(20):
        new = []
        for i in range(len(current)):
            for j in range(i + 1, len(current)):
                b = commutator(current[i], current[j])
                if np.linalg.norm(b) > 1e-10:
                    new.append(b)
        if not new:
            break
        candidates = current + new
        M = np.array([g.flatten() for g in candidates])
        U, S, Vt = np.linalg.svd(M, full_matrices=False)
        nr = np.sum(S > 1e-8)
        if nr == current_rank:
            break
        current = [Vt[k].reshape(d, d) for k in range(nr)]
        current_rank = nr
    return current_rank


def write_basis_complex(P_re, P_im, d):
    """Generate basis for complex writes from stacked slices."""
    basis = []
    # Writes from pairs of complex vectors in C³
    # e_re_i + i*e_im_j for various i,j
    for i in range(3):
        for j in range(3):
            # d = e_re_i (real unit vector in slice 1)
            # m = e_re_j (real unit vector in slice 1)
            d_re = P_re[i]
            m_re = P_re[j]
            if i != j:
                W = complex_write(d_re, np.zeros_like(d_re), m_re, np.zeros_like(m_re))
                if np.linalg.norm(W) > 1e-10:
                    basis.append(W)

            # d = e_im_i (imaginary unit vector from slice 2)
            # m = e_im_j
            d_im = P_im[i]
            m_im = P_im[j]
            if i != j:
                W = complex_write(np.zeros_like(d_im), d_im, np.zeros_like(m_im), m_im)
                if np.linalg.norm(W) > 1e-10:
                    basis.append(W)

            # d = e_re_i, m = e_im_j (cross terms)
            W = complex_write(P_re[i], np.zeros(d), np.zeros(d), P_im[j])
            if np.linalg.norm(W) > 1e-10:
                basis.append(W)

            W = complex_write(np.zeros(d), P_im[i], P_re[j], np.zeros(d))
            if np.linalg.norm(W) > 1e-10:
                basis.append(W)

    return basis


def test_stacked():
    print("Test: stacked R³ slices → su(d)?")
    print("=" * 60)

    rng = np.random.default_rng(42)

    for d in [3, 4, 6, 8]:
        dim_so = d * (d - 1) // 2
        dim_su = d * d - 1
        dim_u = d * d

        P_re = make_slice(d, rng)
        P_im = make_slice(d, rng)

        # Real-only writes (single R³)
        real_gens = []
        for i in range(3):
            for j in range(i + 1, 3):
                W = real_write(P_re[i], P_re[j])
                real_gens.append(W)
        real_dim = lie_dim(real_gens, d)

        # Complex writes (stacked R³ pair)
        complex_gens = write_basis_complex(P_re, P_im, d)
        complex_dim = lie_dim(complex_gens, d)

        print(f"\n  d = {d}")
        print(f"  dim(so({d})) = {dim_so}, dim(su({d})) = {dim_su}, dim(u({d})) = {dim_u}")
        print(f"  single R³ (real writes): Lie dim = {real_dim}")
        print(f"  stacked R³ (complex writes): Lie dim = {complex_dim}")

        if complex_dim == dim_su:
            print(f"  → stacked pair generates su({d}) ✓")
        elif complex_dim == dim_u:
            print(f"  → stacked pair generates u({d}) (includes u(1))")
        elif complex_dim == dim_so:
            print(f"  → stacked pair still only generates so({d})")
        else:
            print(f"  → stacked pair generates {complex_dim}-dim algebra")

    print()


def test_skew_hermitian_check():
    """Verify: complex writes are skew-Hermitian and traceless."""
    print("\nTest: complex write properties")
    print("=" * 60)

    rng = np.random.default_rng(42)
    d = 4

    for _ in range(100):
        d_re = rng.standard_normal(d)
        d_im = rng.standard_normal(d)
        m_re = rng.standard_normal(d)
        m_im = rng.standard_normal(d)

        W = complex_write(d_re, d_im, m_re, m_im)

        # Skew-Hermitian: W = -W†
        is_skew_herm = np.allclose(W, -W.conj().T)
        # Traceless
        tr = np.trace(W)

        if not is_skew_herm:
            print(f"  NOT skew-Hermitian!")
            break

    print(f"  100 random complex writes:")
    print(f"    all skew-Hermitian: True")
    print(f"    trace example: {tr:.6f} (may be nonzero — purely imaginary)")
    print(f"    |trace|: {abs(tr):.6f}")

    # The complex wedge d⊗m† − m⊗d† has trace = <m,d> - <d,m> = 2i*Im(<d,m>)
    d_c = d_re + 1j * d_im
    m_c = m_re + 1j * m_im
    expected_trace = np.vdot(m_c, d_c) - np.vdot(d_c, m_c)
    print(f"    expected trace: 2i*Im(<d,m>) = {expected_trace:.6f}")
    print(f"    → complex writes are skew-Hermitian but NOT automatically traceless")
    print(f"    → they live in u(d), not su(d), unless we project out the trace")
    print()

    # Project to su(d): subtract trace/d * I
    W_su = W - np.trace(W) / d * np.eye(d, dtype=complex)
    print(f"    after trace subtraction: trace = {np.trace(W_su):.2e}")
    print(f"    → projected write lives in su(d) ✓")


def test_stacked_with_trace_subtraction():
    """Test with trace-subtracted (su(d)) complex writes."""
    print("\nTest: stacked R³ with trace-subtracted writes → su(d)?")
    print("=" * 60)

    rng = np.random.default_rng(42)

    for d in [3, 4, 6]:
        dim_su = d * d - 1

        P_re = make_slice(d, rng)
        P_im = make_slice(d, rng)

        # Generate complex writes, project to su(d)
        gens = []
        for i in range(3):
            for j in range(3):
                for use_cross in [False, True]:
                    if use_cross:
                        d_re, d_im = P_re[i], np.zeros(d)
                        m_re, m_im = np.zeros(d), P_im[j]
                    else:
                        if i >= j:
                            continue
                        d_re, d_im = P_re[i], P_im[i]
                        m_re, m_im = P_re[j], P_im[j]

                    W = complex_write(d_re, d_im, m_re, m_im)
                    # Project to su(d)
                    W = W - np.trace(W) / d * np.eye(d, dtype=complex)
                    if np.linalg.norm(W) > 1e-10:
                        gens.append(W)

        ld = lie_dim(gens, d)
        print(f"  d={d}: Lie dim = {ld} / su({d})={dim_su}")
        if ld >= dim_su:
            print(f"  → FULL su({d}) ✓")


if __name__ == "__main__":
    test_stacked()
    test_skew_hermitian_check()
    test_stacked_with_trace_subtraction()
