"""
Test: WHY does stacking two R³ slices as C³ produce su(d)?

The existing test (test_stacked_slices.py) shows that it works.
This test asks what forces the complex structure.

Hypothesis: given two R³ slices, the complex structure J (mapping one
to the other, with J² = -I) is the UNIQUE minimal extension that
escapes so(d). Specifically:

1. Two independent real slices, used independently, cannot escape so(d).
   Real cross-terms (d from slice 1, m from slice 2) are still real
   skew-symmetric — still so(d).

2. To reach su(d) you need imaginary-symmetric matrices (iS where S
   is real symmetric). These are the directions in su(d) \ so(d).

3. The complex structure J is what introduces the imaginary part.
   J² = -I is forced: J² = +I (a mere swap/reflection) doesn't give
   you a complex structure and can't produce the imaginary-symmetric
   directions.

4. Two subspaces of equal dimension carry a canonical J (up to SO(3)
   rotation within each slice). The stacking is not an additional
   assumption — it's recognition of structure already present in the
   pairing.
"""

import numpy as np
from foam import random_slice


def lie_dim(generators, d):
    """Dimension of Lie algebra generated by closing under commutators."""
    current = list(generators)
    if not current:
        return 0
    M = np.array([g.flatten() for g in current])
    current_rank = np.linalg.matrix_rank(M, tol=1e-8)

    for _ in range(30):
        new = []
        for i in range(len(current)):
            for j in range(i + 1, len(current)):
                b = current[i] @ current[j] - current[j] @ current[i]
                if np.linalg.norm(b) > 1e-10:
                    new.append(b)
        if not new:
            break
        candidates = current + new
        M = np.array([g.flatten() for g in candidates])
        U, S, Vt = np.linalg.svd(M, full_matrices=False)
        nr = np.sum(S > 1e-8)
        if nr == current_rank:
            break
        current = [Vt[k].reshape(d, d) for k in range(nr)]
        current_rank = nr
    return current_rank


def test_real_cross_terms_stay_in_so():
    """Two real slices with cross-terms: do they escape so(d)?"""
    print("Test 1: real cross-terms between two slices")
    print("=" * 60)

    rng = np.random.default_rng(42)

    for d in [4, 6]:
        P1 = random_slice(d, rng=rng)
        P2 = random_slice(d, rng=rng)

        gens = []
        # All real wedge products: within-slice AND cross-slice
        for P_a in [P1, P2]:
            for P_b in [P1, P2]:
                for i in range(3):
                    for j in range(3):
                        if P_a is P_b and i >= j:
                            continue
                        d_vec = P_a[i]
                        m_vec = P_b[j]
                        W = np.outer(d_vec, m_vec) - np.outer(m_vec, d_vec)
                        if np.linalg.norm(W) > 1e-10:
                            gens.append(W)

        ld = lie_dim(gens, d)
        dim_so = d * (d - 1) // 2
        dim_su = d * d - 1

        # Check: are all generators real skew-symmetric?
        all_real_skew = all(
            np.allclose(g, -g.T) and np.allclose(g.imag, 0)
            for g in gens
        )

        print(f"  d={d}: generated Lie dim = {ld}")
        print(f"    so({d}) = {dim_so}, su({d}) = {dim_su}")
        print(f"    all generators real skew-symmetric: {all_real_skew}")
        print(f"    → {'cannot escape so(d)' if ld <= dim_so else 'ESCAPED so(d)!'}")
        print()


def test_j_squared():
    """Show that J² = -I (complex structure) vs J² = +I (swap) makes
    the difference between su(d) and so(d)."""
    print("Test 2: J² = -I vs J² = +I")
    print("=" * 60)

    rng = np.random.default_rng(42)
    d = 4

    P1 = random_slice(d, rng=rng)
    P2 = random_slice(d, rng=rng)

    # Ensure orthogonal slices for clean separation
    # Use Gram-Schmidt on P2 against P1
    P2_orth = P2.copy()
    for i in range(3):
        for j in range(3):
            P2_orth[i] -= np.dot(P2_orth[i], P1[j]) * P1[j]
        P2_orth[i] /= np.linalg.norm(P2_orth[i])

    # Re-orthogonalize P2_orth within itself
    for i in range(1, 3):
        for j in range(i):
            P2_orth[i] -= np.dot(P2_orth[i], P2_orth[j]) * P2_orth[j]
        P2_orth[i] /= np.linalg.norm(P2_orth[i])

    # Verify orthogonality
    cross = P1 @ P2_orth.T
    print(f"  slice orthogonality check: max |P1 . P2| = {np.max(np.abs(cross)):.2e}")

    # --- J² = -I: complex structure ---
    # J maps P1[i] -> P2[i], P2[i] -> -P1[i]
    # Write: (d1 + i*d2) ⊗ (m1 - i*m2) - (m1 + i*m2) ⊗ (d1 - i*d2)
    gens_complex = []
    for i in range(3):
        for j in range(3):
            d_re, d_im = P1[i], P2_orth[i]
            m_re, m_im = P1[j], P2_orth[j]
            d_c = d_re + 1j * d_im
            m_c = m_re + 1j * m_im
            W = np.outer(d_c, m_c.conj()) - np.outer(m_c, d_c.conj())
            if np.linalg.norm(W) > 1e-10:
                gens_complex.append(W)

    ld_complex = lie_dim(gens_complex, d)

    # --- J² = +I: swap/reflection (NOT a complex structure) ---
    # J maps P1[i] -> P2[i], P2[i] -> +P1[i]  (reflection, not rotation)
    # Use "hyperbolic" combination: d1 + d2 (not d1 + i*d2)
    gens_swap = []
    for i in range(3):
        for j in range(3):
            # "swap" combination: treat both as real, add them
            d_plus = P1[i] + P2_orth[i]
            m_plus = P1[j] + P2_orth[j]
            d_minus = P1[i] - P2_orth[i]
            m_minus = P1[j] - P2_orth[j]
            # Various real combinations
            for d_vec, m_vec in [(d_plus, m_plus), (d_plus, m_minus),
                                  (d_minus, m_plus), (d_minus, m_minus)]:
                W = np.outer(d_vec, m_vec) - np.outer(m_vec, d_vec)
                if np.linalg.norm(W) > 1e-10:
                    gens_swap.append(W)

    ld_swap = lie_dim(gens_swap, d)

    dim_so = d * (d - 1) // 2
    dim_su = d * d - 1

    print(f"\n  d = {d}, so({d}) = {dim_so}, su({d}) = {dim_su}")
    print(f"  J² = -I (complex structure): Lie dim = {ld_complex}")
    print(f"  J² = +I (swap/reflection):   Lie dim = {ld_swap}")
    print(f"\n  → J² = -I {'reaches su(d)' if ld_complex >= dim_su else 'does NOT reach su(d)'}")
    print(f"  → J² = +I {'reaches su(d)' if ld_swap >= dim_su else 'stays in so(d)'}")
    print()


def test_imaginary_symmetric_directions():
    """Show exactly which directions in su(d) are missing from so(d),
    and that J is what produces them."""
    print("Test 3: anatomy of su(d) \\ so(d)")
    print("=" * 60)

    d = 4
    dim_so = d * (d - 1) // 2  # 6
    dim_su = d * d - 1          # 15

    print(f"  d = {d}")
    print(f"  so({d}) has {dim_so} dimensions: real skew-symmetric matrices")
    print(f"  su({d}) has {dim_su} dimensions: traceless skew-Hermitian matrices")
    print(f"  su({d}) \\ so({d}) has {dim_su - dim_so} dimensions: i * (real symmetric traceless)")
    print()

    # Build explicit basis for su(d) \ so(d)
    # These are matrices of the form i*S where S is real, symmetric, traceless
    missing_directions = []

    # i * (e_j e_k^T + e_k e_j^T) for j < k: symmetric off-diagonal
    for j in range(d):
        for k in range(j + 1, d):
            S = np.zeros((d, d))
            S[j, k] = S[k, j] = 1.0
            missing_directions.append(1j * S)

    # i * (e_j e_j^T - e_k e_k^T) for j < k: traceless symmetric diagonal
    for j in range(d - 1):
        S = np.zeros((d, d))
        S[j, j] = 1.0
        S[j + 1, j + 1] = -1.0
        missing_directions.append(1j * S)

    print(f"  constructed {len(missing_directions)} missing directions")
    for m in missing_directions:
        assert np.allclose(m, -m.conj().T), "not skew-Hermitian!"
    print(f"  all are skew-Hermitian: True")

    # Now show: a complex write produces components in these directions
    rng = np.random.default_rng(42)
    d_re = rng.standard_normal(d)
    d_im = rng.standard_normal(d)
    m_re = rng.standard_normal(d)
    m_im = rng.standard_normal(d)

    d_c = d_re + 1j * d_im
    m_c = m_re + 1j * m_im
    W = np.outer(d_c, m_c.conj()) - np.outer(m_c, d_c.conj())

    # Decompose W into so(d) part and imaginary-symmetric part
    W_so = 0.5 * (W - W.T).real  # real skew-symmetric part (so(d))
    W_is = W - W_so  # remainder (should be purely imaginary symmetric + trace)

    print(f"\n  complex write decomposition:")
    print(f"    ||W||        = {np.linalg.norm(W):.4f}")
    print(f"    ||W_so(d)||  = {np.linalg.norm(W_so):.4f} (real skew-symmetric)")
    print(f"    ||W_rest||   = {np.linalg.norm(W_is):.4f} (imaginary symmetric + trace)")

    # The imaginary-symmetric part: check it's i * real symmetric
    W_is_check = 0.5 * (W + W.T)  # symmetric part of W (should be purely imaginary)
    is_pure_imag = np.allclose(W_is_check.real, 0)
    print(f"    symmetric part is purely imaginary: {is_pure_imag}")

    # Real-only write for comparison
    W_real = np.outer(d_re, m_re) - np.outer(m_re, d_re)
    W_real_sym = 0.5 * (W_real + W_real.T)
    print(f"\n  real write decomposition:")
    print(f"    ||W_real||     = {np.linalg.norm(W_real):.4f}")
    print(f"    ||symmetric||  = {np.linalg.norm(W_real_sym):.2e} (should be ~0)")
    print(f"    → real writes have NO imaginary-symmetric component")
    print(f"    → they literally cannot reach su(d) \\ so(d)")
    print()


def test_j_is_canonical():
    """Show that the specific J doesn't matter — all choices of pairing
    produce the same Lie algebra."""
    print("Test 4: J is canonical up to SO(3)")
    print("=" * 60)

    rng = np.random.default_rng(42)
    d = 4

    P1 = random_slice(d, rng=rng)
    P2 = random_slice(d, rng=rng)

    # Make P2 orthogonal to P1
    P2_orth = P2.copy()
    for i in range(3):
        for j in range(3):
            P2_orth[i] -= np.dot(P2_orth[i], P1[j]) * P1[j]
        P2_orth[i] /= np.linalg.norm(P2_orth[i])
    for i in range(1, 3):
        for j in range(i):
            P2_orth[i] -= np.dot(P2_orth[i], P2_orth[j]) * P2_orth[j]
        P2_orth[i] /= np.linalg.norm(P2_orth[i])

    dims = []
    # Try several different SO(3) rotations of the pairing
    for trial in range(5):
        # Random SO(3) rotation applied to P2_orth
        R = np.linalg.qr(rng.standard_normal((3, 3)))[0]
        if np.linalg.det(R) < 0:
            R[:, 0] *= -1
        P2_rot = R @ P2_orth  # rotate within the second slice

        gens = []
        for i in range(3):
            for j in range(3):
                d_c = P1[i] + 1j * P2_rot[i]
                m_c = P1[j] + 1j * P2_rot[j]
                W = np.outer(d_c, m_c.conj()) - np.outer(m_c, d_c.conj())
                if np.linalg.norm(W) > 1e-10:
                    gens.append(W)

        ld = lie_dim(gens, d)
        dims.append(ld)
        print(f"  trial {trial}: SO(3) rotation → Lie dim = {ld}")

    all_same = len(set(dims)) == 1
    print(f"\n  all trials give same dimension: {all_same}")
    print(f"  → the Lie algebra depends on the slices, not the pairing")
    print()


def test_why_two():
    """Why exactly two slices? Not one, not three."""
    print("Test 5: why two slices?")
    print("=" * 60)

    rng = np.random.default_rng(42)
    d = 6

    dim_so = d * (d - 1) // 2
    dim_su = d * d - 1

    # One slice: stays in so(d) subalgebra
    P1 = random_slice(d, rng=rng)
    gens_1 = []
    for i in range(3):
        for j in range(i + 1, 3):
            W = np.outer(P1[i], P1[j]) - np.outer(P1[j], P1[i])
            gens_1.append(W)
    ld_1 = lie_dim(gens_1, d)

    # Two slices stacked as C³
    P2 = random_slice(d, rng=rng)
    gens_2 = []
    for i in range(3):
        for j in range(3):
            d_c = P1[i] + 1j * P2[i]
            m_c = P1[j] + 1j * P2[j]
            W = np.outer(d_c, m_c.conj()) - np.outer(m_c, d_c.conj())
            if np.linalg.norm(W) > 1e-10:
                gens_2.append(W)
    ld_2 = lie_dim(gens_2, d)

    # Three slices: stack as... what? C³ only uses two.
    # Try: three slices, each pair stacked
    P3 = random_slice(d, rng=rng)
    gens_3 = []
    for Pa, Pb in [(P1, P2), (P1, P3), (P2, P3)]:
        for i in range(3):
            for j in range(3):
                d_c = Pa[i] + 1j * Pb[i]
                m_c = Pa[j] + 1j * Pb[j]
                W = np.outer(d_c, m_c.conj()) - np.outer(m_c, d_c.conj())
                if np.linalg.norm(W) > 1e-10:
                    gens_3.append(W)
    ld_3 = lie_dim(gens_3, d)

    print(f"  d = {d}, so({d}) = {dim_so}, su({d}) = {dim_su}")
    print(f"  1 slice (real):           Lie dim = {ld_1}")
    print(f"  2 slices (stacked C³):    Lie dim = {ld_2}")
    print(f"  3 slices (pairwise C³):   Lie dim = {ld_3}")
    print()
    print(f"  → one slice: so(3) subalgebra")
    print(f"  → two slices: {'su(d) or u(d)' if ld_2 >= dim_su else f'{ld_2}-dim algebra'}")
    print(f"  → three slices: {'same algebra' if ld_3 == ld_2 else f'larger: {ld_3}-dim'}")
    print(f"  → two is sufficient. third doesn't add algebraic reach.")
    print()


if __name__ == "__main__":
    test_real_cross_terms_stay_in_so()
    test_j_squared()
    test_imaginary_symmetric_directions()
    test_j_is_canonical()
    test_why_two()
