"""
Test: does generic controllability hold?

For random R³ slices on Gr(3, d), do the Lie brackets of
the write subalgebras span su(d)?

Each observer's writes generate a 3-dim subalgebra of su(d).
The commutators of overlapping observers' writes generate more.
Question: for how many observers with generic slices do you
span all of su(d)?

This is computationally settleable for small d.
"""

import numpy as np
from foam import random_slice


def write_basis(P):
    """Generate a basis for the Lie algebra elements this observer can write.

    The observer writes d⊗m - m⊗d where d, m are in the observer's R³.
    The space of such writes is spanned by e_i⊗e_j - e_j⊗e_i for
    i < j where e_i are the observer's basis vectors (rows of P lifted to R^d).

    Returns a list of d×d skew-symmetric matrices (a basis for the
    observer's write subalgebra).
    """
    d = P.shape[1]
    basis = []
    # P rows are orthonormal vectors in R^d
    for i in range(3):
        for j in range(i + 1, 3):
            ei = P[i]  # (d,)
            ej = P[j]  # (d,)
            W = np.outer(ei, ej) - np.outer(ej, ei)
            basis.append(W)
    return basis  # 3 matrices (for C(3,2) = 3)


def commutator(A, B):
    return A @ B - B @ A


def lie_algebra_dimension(generators, d):
    """Compute the dimension of the Lie algebra generated by a set of matrices.

    Uses repeated bracketing until no new independent elements appear.
    """
    # Flatten each generator to a vector
    n = d * d
    vectors = [g.flatten() for g in generators]

    def rank(vecs):
        if not vecs:
            return 0
        M = np.array(vecs)
        return np.linalg.matrix_rank(M, tol=1e-8)

    current = list(generators)
    current_rank = rank([g.flatten() for g in current])

    for iteration in range(20):  # max iterations
        new_elements = []
        for i in range(len(current)):
            for j in range(i + 1, len(current)):
                bracket = commutator(current[i], current[j])
                if np.linalg.norm(bracket) > 1e-10:
                    new_elements.append(bracket)

        if not new_elements:
            break

        # Add new elements and check rank
        candidates = current + new_elements
        new_rank = rank([g.flatten() for g in candidates])

        if new_rank == current_rank:
            break  # no new independent elements

        # Keep only independent elements (thin the set)
        M = np.array([g.flatten() for g in candidates])
        # Use SVD to find independent subset
        U, S, Vt = np.linalg.svd(M, full_matrices=False)
        n_indep = np.sum(S > 1e-8)
        # Reconstruct independent elements from top singular vectors
        current = [Vt[k].reshape(d, d) for k in range(n_indep)]
        current_rank = n_indep

    return current_rank


def test_controllability():
    print("Test: generic controllability")
    print("=" * 60)

    rng = np.random.default_rng(42)

    for d in [3, 4, 5, 6, 8]:
        dim_su = d * d - 1  # dimension of su(d)
        print(f"\n  d = {d}, dim(su({d})) = {dim_su}")
        print(f"  {'—' * 40}")

        # Test with increasing numbers of observers
        for n_obs in range(1, min(d * d, 20)):
            slices = [random_slice(d, rng=rng) for _ in range(n_obs)]

            # Gather all write basis elements
            all_generators = []
            for P in slices:
                all_generators.extend(write_basis(P))

            # Compute Lie algebra dimension
            lie_dim = lie_algebra_dimension(all_generators, d)

            if lie_dim >= dim_su:
                print(f"    {n_obs} observers: Lie dim = {lie_dim} = dim(su({d})). "
                      f"FULL CONTROLLABILITY ✓")
                break
            else:
                print(f"    {n_obs} observers: Lie dim = {lie_dim} / {dim_su}")

        # Now test genericity: is it ALWAYS achievable with that many observers?
        n_needed = n_obs
        n_trials = 100
        successes = 0
        for trial in range(n_trials):
            trial_rng = np.random.default_rng(trial * 1000 + d)
            slices = [random_slice(d, rng=trial_rng) for _ in range(n_needed)]
            all_generators = []
            for P in slices:
                all_generators.extend(write_basis(P))
            lie_dim = lie_algebra_dimension(all_generators, d)
            if lie_dim >= dim_su:
                successes += 1

        print(f"    → {n_needed} observers sufficient: {successes}/{n_trials} trials")
        if successes == n_trials:
            print(f"    → GENERIC controllability with {n_needed} observers ✓")
        else:
            # Try with one more
            n_needed += 1
            successes2 = 0
            for trial in range(n_trials):
                trial_rng = np.random.default_rng(trial * 1000 + d + 500)
                slices = [random_slice(d, rng=trial_rng) for _ in range(n_needed)]
                all_generators = []
                for P in slices:
                    all_generators.extend(write_basis(P))
                lie_dim = lie_algebra_dimension(all_generators, d)
                if lie_dim >= dim_su:
                    successes2 += 1
            print(f"    → {n_needed} observers: {successes2}/{n_trials} trials")


if __name__ == "__main__":
    test_controllability()
